include $(THEOS)/makefiles/common.mk

TOOL_NAME = LiquidAssJetsam

LiquidAssJetsam_FILES = main.m
LiquidAssJetsam_CFLAGS = -fobjc-arc
LiquidAssJetsam_FRAMEWORKS = Foundation
LiquidAssJetsam_CODESIGN_FLAGS = -Sentitlements.plist
LiquidAssJetsam_INSTALL_PATH = /usr/local/bin

include $(THEOS_MAKE_PATH)/tool.mk
